server:
  port: 8080

spring:
  cors:
    allowOrigin: '*'
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: thibault
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: true
  main:
    web-application-type: servlet
